# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: flask-app
#   name: flask-app
# spec:
#   ports:
#   - port: 5000
#     protocol: TCP
#     targetPort: 5090
#   selector:
#     app: flask-app
#   type: LoadBalancer
# status:
#   loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8190
  type: NodePort
